-- ======================RFM Segmentation on Sales Data=======================

-- Step 1: Create the Database and Table

CREATE DATABASE rfm_analysis;

USE rfm_analysis;

CREATE TABLE rfm_data(
ORDERNU INT,
QUANTITY INT,
PRICEEACI DECIMAL(10,2),
ORDERLIN INT,
SALES DECIMAL(10,2),
ORDERDA DATE,
STATUS VARCHAR(20),
QTRID INT,
MONTHIC INT,
YEARID INT,
PRODUCTIMSRP DECIMAL(10,2),
PRODUCTI VARCHAR(50),
CUSTOMEI INT,
PHONE VARCHAR(20),
ADDRESSL1 VARCHAR(100),
ADDRESSL2 VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTALCO VARCHAR(20),
COUNTRY VARCHAR(50),
TERRITROY VARCHAR(50),
CONTACTI VARCHAR(50),
CONTACTI2 VARCHAR(50),
DEALSIZE VARCHAR(20)
);


-- Inspecting Data
SELECT * FROM rfm_data LIMIT 10;

-- unique values
SELECT DISTINCT status from rfm_data;

SELECT DISTINCT status from rfm_data;
SELECT DISTINCT COUNTRY from rfm_data;

SELECT DISTINCT YEARID from rfm_data;
SELECT DISTINCT PRODUCTI from rfm_data;

SELECT DISTINCT DEALSIZE from rfm_data;
SELECT DISTINCT TERRITROY from rfm_data;


-- ==================================================

















