-- ======================RFM Segmentation on Sales Data=======================

-- Step 1: Create the Database and Table

CREATE DATABASE rfm_analysis;

USE rfm_analysis;

CREATE TABLE rfm_data(
ORDERNU INT,
QUANTITY INT,
PRICEEACI DECIMAL(10,2),
ORDERLIN INT,
SALES DECIMAL(10,2),
ORDERDA DATE,
STATUS VARCHAR(20),
QTRID INT,
PRODUCTIMSRP DECIMAL(10,2),
PRODUCTI VARCHAR(50),
CUSTOMEI INT,
PHONE VARCHAR(20),
ADDRESSL1 VARCHAR(100),
ADDRESSL2 VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTALCO VARCHAR(20),
COUNTRY VARCHAR(50),
TERRITROY VARCHAR(50),
CONTACTI VARCHAR(50),
CONTACTI2 VARCHAR(50),
DEALSIZE VARCHAR(20)
);